import { dictionary } from '@rotamer/i18n';

/**
 * O texto dos primitivos.
 *
 * São dois, e os dois carregam significado de produto: o selo de origem, que
 * diz se o número foi calculado ou gerado, e nada mais.
 */
export const sourceBadgeMessages = dictionary({
  'pt-BR': {
    computed: 'calculado',
    generated: 'hipótese da IA',
    computedTitle: 'Valor calculado pelo RDKit ou pelo motor de missões.',
    generatedTitle: 'Texto gerado por modelo de linguagem. É hipótese, não medida.',
  },

  en: {
    computed: 'computed',
    generated: 'AI hypothesis',
    computedTitle: 'Value computed by RDKit or by the mission engine.',
    generatedTitle: 'Text generated by a language model. It is a hypothesis, not a measurement.',
  },
});
