import { elementSymbol } from '@rotamer/core';

/**
 * A tabela periódica inteira.
 *
 * A barra de ferramentas mostra os elementos que aparecem em prova de orgânica;
 * o resto da tabela mora aqui, atrás de um botão. Química não é só carbono e
 * oxigênio, e um aluno que precisa de ferro ou de silício não deveria descobrir
 * que a ferramenta não tem.
 *
 * Cada entrada é o número atômico, o grupo e o período — a posição na grade. As
 * duas últimas faixas são lantanídeos e actinídeos, que a tabela sempre desenha
 * embaixo para não ficar com dezoito colunas a mais.
 */

/** `[número atômico, grupo, período]`. Período 8 e 9 são as faixas de baixo. */
const LAYOUT: readonly (readonly [number, number, number])[] = [
  [1, 1, 1],
  [2, 18, 1],
  [3, 1, 2],
  [4, 2, 2],
  [5, 13, 2],
  [6, 14, 2],
  [7, 15, 2],
  [8, 16, 2],
  [9, 17, 2],
  [10, 18, 2],
  [11, 1, 3],
  [12, 2, 3],
  [13, 13, 3],
  [14, 14, 3],
  [15, 15, 3],
  [16, 16, 3],
  [17, 17, 3],
  [18, 18, 3],
  [19, 1, 4],
  [20, 2, 4],
  [21, 3, 4],
  [22, 4, 4],
  [23, 5, 4],
  [24, 6, 4],
  [25, 7, 4],
  [26, 8, 4],
  [27, 9, 4],
  [28, 10, 4],
  [29, 11, 4],
  [30, 12, 4],
  [31, 13, 4],
  [32, 14, 4],
  [33, 15, 4],
  [34, 16, 4],
  [35, 17, 4],
  [36, 18, 4],
  [37, 1, 5],
  [38, 2, 5],
  [39, 3, 5],
  [40, 4, 5],
  [41, 5, 5],
  [42, 6, 5],
  [43, 7, 5],
  [44, 8, 5],
  [45, 9, 5],
  [46, 10, 5],
  [47, 11, 5],
  [48, 12, 5],
  [49, 13, 5],
  [50, 14, 5],
  [51, 15, 5],
  [52, 16, 5],
  [53, 17, 5],
  [54, 18, 5],
  [55, 1, 6],
  [56, 2, 6],
  [57, 3, 8],
  [58, 4, 8],
  [59, 5, 8],
  [60, 6, 8],
  [61, 7, 8],
  [62, 8, 8],
  [63, 9, 8],
  [64, 10, 8],
  [65, 11, 8],
  [66, 12, 8],
  [67, 13, 8],
  [68, 14, 8],
  [69, 15, 8],
  [70, 16, 8],
  [71, 17, 8],
  [72, 4, 6],
  [73, 5, 6],
  [74, 6, 6],
  [75, 7, 6],
  [76, 8, 6],
  [77, 9, 6],
  [78, 10, 6],
  [79, 11, 6],
  [80, 12, 6],
  [81, 13, 6],
  [82, 14, 6],
  [83, 15, 6],
  [84, 16, 6],
  [85, 17, 6],
  [86, 18, 6],
  [87, 1, 7],
  [88, 2, 7],
  [89, 3, 9],
  [90, 4, 9],
  [91, 5, 9],
  [92, 6, 9],
  [93, 7, 9],
  [94, 8, 9],
  [95, 9, 9],
  [96, 10, 9],
  [97, 11, 9],
  [98, 12, 9],
  [99, 13, 9],
  [100, 14, 9],
  [101, 15, 9],
  [102, 16, 9],
  [103, 17, 9],
  [104, 4, 7],
  [105, 5, 7],
  [106, 6, 7],
  [107, 7, 7],
  [108, 8, 7],
  [109, 9, 7],
  [110, 10, 7],
  [111, 11, 7],
  [112, 12, 7],
  [113, 13, 7],
  [114, 14, 7],
  [115, 15, 7],
  [116, 16, 7],
  [117, 17, 7],
  [118, 18, 7],
];

export interface TableEntry {
  readonly z: number;
  readonly symbol: string;
  readonly group: number;
  readonly period: number;
}

/** A tabela pronta para desenhar, com o símbolo vindo do núcleo. */
export const PERIODIC_TABLE: readonly TableEntry[] = LAYOUT.map(([z, group, period]) => ({
  z,
  symbol: elementSymbol(z),
  group,
  period,
}));

/** O nome em português de cada elemento — é por ele que a busca da tabela acha. */
export const ELEMENT_NAMES: Readonly<Record<string, string>> = {
  H: 'Hidrogênio',
  He: 'Hélio',
  Li: 'Lítio',
  Be: 'Berílio',
  B: 'Boro',
  C: 'Carbono',
  N: 'Nitrogênio',
  O: 'Oxigênio',
  F: 'Flúor',
  Ne: 'Neônio',
  Na: 'Sódio',
  Mg: 'Magnésio',
  Al: 'Alumínio',
  Si: 'Silício',
  P: 'Fósforo',
  S: 'Enxofre',
  Cl: 'Cloro',
  Ar: 'Argônio',
  K: 'Potássio',
  Ca: 'Cálcio',
  Sc: 'Escândio',
  Ti: 'Titânio',
  V: 'Vanádio',
  Cr: 'Cromo',
  Mn: 'Manganês',
  Fe: 'Ferro',
  Co: 'Cobalto',
  Ni: 'Níquel',
  Cu: 'Cobre',
  Zn: 'Zinco',
  Ga: 'Gálio',
  Ge: 'Germânio',
  As: 'Arsênio',
  Se: 'Selênio',
  Br: 'Bromo',
  Kr: 'Criptônio',
  Rb: 'Rubídio',
  Sr: 'Estrôncio',
  Y: 'Ítrio',
  Zr: 'Zircônio',
  Nb: 'Nióbio',
  Mo: 'Molibdênio',
  Tc: 'Tecnécio',
  Ru: 'Rutênio',
  Rh: 'Ródio',
  Pd: 'Paládio',
  Ag: 'Prata',
  Cd: 'Cádmio',
  In: 'Índio',
  Sn: 'Estanho',
  Sb: 'Antimônio',
  Te: 'Telúrio',
  I: 'Iodo',
  Xe: 'Xenônio',
  Cs: 'Césio',
  Ba: 'Bário',
  La: 'Lantânio',
  Ce: 'Cério',
  Pr: 'Praseodímio',
  Nd: 'Neodímio',
  Pm: 'Promécio',
  Sm: 'Samário',
  Eu: 'Európio',
  Gd: 'Gadolínio',
  Tb: 'Térbio',
  Dy: 'Disprósio',
  Ho: 'Hólmio',
  Er: 'Érbio',
  Tm: 'Túlio',
  Yb: 'Itérbio',
  Lu: 'Lutécio',
  Hf: 'Háfnio',
  Ta: 'Tântalo',
  W: 'Tungstênio',
  Re: 'Rênio',
  Os: 'Ósmio',
  Ir: 'Irídio',
  Pt: 'Platina',
  Au: 'Ouro',
  Hg: 'Mercúrio',
  Tl: 'Tálio',
  Pb: 'Chumbo',
  Bi: 'Bismuto',
  Po: 'Polônio',
  At: 'Astato',
  Rn: 'Radônio',
  Fr: 'Frâncio',
  Ra: 'Rádio',
  Ac: 'Actínio',
  Th: 'Tório',
  Pa: 'Protactínio',
  U: 'Urânio',
  Np: 'Netúnio',
  Pu: 'Plutônio',
  Am: 'Amerício',
  Cm: 'Cúrio',
  Bk: 'Berquélio',
  Cf: 'Califórnio',
  Es: 'Einstênio',
  Fm: 'Férmio',
  Md: 'Mendelévio',
  No: 'Nobélio',
  Lr: 'Laurêncio',
  Rf: 'Rutherfórdio',
  Db: 'Dúbnio',
  Sg: 'Seabórgio',
  Bh: 'Bóhrio',
  Hs: 'Hássio',
  Mt: 'Meitnério',
  Ds: 'Darmstácio',
  Rg: 'Roentgênio',
  Cn: 'Copernício',
  Nh: 'Nihônio',
  Fl: 'Fleróvio',
  Mc: 'Moscóvio',
  Lv: 'Livermório',
  Ts: 'Tenessino',
  Og: 'Oganessônio'
};

/** Bloco da tabela: s, p, d ou f. É o que dá o tom de fundo de cada célula. */
export type ElementBlock = 's' | 'p' | 'd' | 'f';

export function blockOf(entry: TableEntry): ElementBlock {
  if (entry.period >= 8) return 'f';
  if (entry.group <= 2) return entry.z === 2 ? 'p' : 's';
  if (entry.group >= 13) return 'p';
  return 'd';
}

/** Os que aparecem na barra de ferramentas, sem precisar abrir a tabela. */
export const COMMON_ELEMENTS = ['C', 'N', 'O', 'S', 'P', 'F', 'Cl', 'Br', 'I'] as const;

/** Onde a faixa de lantanídeos e actinídeos começa. */
export const INNER_PERIODS = [8, 9] as const;
