import { dictionary, pick, type Locale } from '@rotamer/i18n';

/**
 * O nome de cada elemento, nos dois idiomas.
 *
 * Não é enfeite de acessibilidade: é por ele que a busca da tabela acha. Quem
 * digita "silício" e quem digita "silicon" procuram a mesma célula, e sem os
 * dois nomes uma das duas buscas devolve tabela vazia.
 *
 * A grafia em inglês é a da IUPAC — Aluminium, Sulfur, Caesium.
 */
export const elementNames = dictionary({
  'pt-BR': {
    H: 'Hidrogênio',
    He: 'Hélio',
    Li: 'Lítio',
    Be: 'Berílio',
    B: 'Boro',
    C: 'Carbono',
    N: 'Nitrogênio',
    O: 'Oxigênio',
    F: 'Flúor',
    Ne: 'Neônio',
    Na: 'Sódio',
    Mg: 'Magnésio',
    Al: 'Alumínio',
    Si: 'Silício',
    P: 'Fósforo',
    S: 'Enxofre',
    Cl: 'Cloro',
    Ar: 'Argônio',
    K: 'Potássio',
    Ca: 'Cálcio',
    Sc: 'Escândio',
    Ti: 'Titânio',
    V: 'Vanádio',
    Cr: 'Cromo',
    Mn: 'Manganês',
    Fe: 'Ferro',
    Co: 'Cobalto',
    Ni: 'Níquel',
    Cu: 'Cobre',
    Zn: 'Zinco',
    Ga: 'Gálio',
    Ge: 'Germânio',
    As: 'Arsênio',
    Se: 'Selênio',
    Br: 'Bromo',
    Kr: 'Criptônio',
    Rb: 'Rubídio',
    Sr: 'Estrôncio',
    Y: 'Ítrio',
    Zr: 'Zircônio',
    Nb: 'Nióbio',
    Mo: 'Molibdênio',
    Tc: 'Tecnécio',
    Ru: 'Rutênio',
    Rh: 'Ródio',
    Pd: 'Paládio',
    Ag: 'Prata',
    Cd: 'Cádmio',
    In: 'Índio',
    Sn: 'Estanho',
    Sb: 'Antimônio',
    Te: 'Telúrio',
    I: 'Iodo',
    Xe: 'Xenônio',
    Cs: 'Césio',
    Ba: 'Bário',
    La: 'Lantânio',
    Ce: 'Cério',
    Pr: 'Praseodímio',
    Nd: 'Neodímio',
    Pm: 'Promécio',
    Sm: 'Samário',
    Eu: 'Európio',
    Gd: 'Gadolínio',
    Tb: 'Térbio',
    Dy: 'Disprósio',
    Ho: 'Hólmio',
    Er: 'Érbio',
    Tm: 'Túlio',
    Yb: 'Itérbio',
    Lu: 'Lutécio',
    Hf: 'Háfnio',
    Ta: 'Tântalo',
    W: 'Tungstênio',
    Re: 'Rênio',
    Os: 'Ósmio',
    Ir: 'Irídio',
    Pt: 'Platina',
    Au: 'Ouro',
    Hg: 'Mercúrio',
    Tl: 'Tálio',
    Pb: 'Chumbo',
    Bi: 'Bismuto',
    Po: 'Polônio',
    At: 'Astato',
    Rn: 'Radônio',
    Fr: 'Frâncio',
    Ra: 'Rádio',
    Ac: 'Actínio',
    Th: 'Tório',
    Pa: 'Protactínio',
    U: 'Urânio',
    Np: 'Netúnio',
    Pu: 'Plutônio',
    Am: 'Amerício',
    Cm: 'Cúrio',
    Bk: 'Berquélio',
    Cf: 'Califórnio',
    Es: 'Einstênio',
    Fm: 'Férmio',
    Md: 'Mendelévio',
    No: 'Nobélio',
    Lr: 'Laurêncio',
    Rf: 'Rutherfórdio',
    Db: 'Dúbnio',
    Sg: 'Seabórgio',
    Bh: 'Bóhrio',
    Hs: 'Hássio',
    Mt: 'Meitnério',
    Ds: 'Darmstácio',
    Rg: 'Roentgênio',
    Cn: 'Copernício',
    Nh: 'Nihônio',
    Fl: 'Fleróvio',
    Mc: 'Moscóvio',
    Lv: 'Livermório',
    Ts: 'Tenessino',
    Og: 'Oganessônio',
  },

  en: {
    H: 'Hydrogen',
    He: 'Helium',
    Li: 'Lithium',
    Be: 'Beryllium',
    B: 'Boron',
    C: 'Carbon',
    N: 'Nitrogen',
    O: 'Oxygen',
    F: 'Fluorine',
    Ne: 'Neon',
    Na: 'Sodium',
    Mg: 'Magnesium',
    Al: 'Aluminium',
    Si: 'Silicon',
    P: 'Phosphorus',
    S: 'Sulfur',
    Cl: 'Chlorine',
    Ar: 'Argon',
    K: 'Potassium',
    Ca: 'Calcium',
    Sc: 'Scandium',
    Ti: 'Titanium',
    V: 'Vanadium',
    Cr: 'Chromium',
    Mn: 'Manganese',
    Fe: 'Iron',
    Co: 'Cobalt',
    Ni: 'Nickel',
    Cu: 'Copper',
    Zn: 'Zinc',
    Ga: 'Gallium',
    Ge: 'Germanium',
    As: 'Arsenic',
    Se: 'Selenium',
    Br: 'Bromine',
    Kr: 'Krypton',
    Rb: 'Rubidium',
    Sr: 'Strontium',
    Y: 'Yttrium',
    Zr: 'Zirconium',
    Nb: 'Niobium',
    Mo: 'Molybdenum',
    Tc: 'Technetium',
    Ru: 'Ruthenium',
    Rh: 'Rhodium',
    Pd: 'Palladium',
    Ag: 'Silver',
    Cd: 'Cadmium',
    In: 'Indium',
    Sn: 'Tin',
    Sb: 'Antimony',
    Te: 'Tellurium',
    I: 'Iodine',
    Xe: 'Xenon',
    Cs: 'Caesium',
    Ba: 'Barium',
    La: 'Lanthanum',
    Ce: 'Cerium',
    Pr: 'Praseodymium',
    Nd: 'Neodymium',
    Pm: 'Promethium',
    Sm: 'Samarium',
    Eu: 'Europium',
    Gd: 'Gadolinium',
    Tb: 'Terbium',
    Dy: 'Dysprosium',
    Ho: 'Holmium',
    Er: 'Erbium',
    Tm: 'Thulium',
    Yb: 'Ytterbium',
    Lu: 'Lutetium',
    Hf: 'Hafnium',
    Ta: 'Tantalum',
    W: 'Tungsten',
    Re: 'Rhenium',
    Os: 'Osmium',
    Ir: 'Iridium',
    Pt: 'Platinum',
    Au: 'Gold',
    Hg: 'Mercury',
    Tl: 'Thallium',
    Pb: 'Lead',
    Bi: 'Bismuth',
    Po: 'Polonium',
    At: 'Astatine',
    Rn: 'Radon',
    Fr: 'Francium',
    Ra: 'Radium',
    Ac: 'Actinium',
    Th: 'Thorium',
    Pa: 'Protactinium',
    U: 'Uranium',
    Np: 'Neptunium',
    Pu: 'Plutonium',
    Am: 'Americium',
    Cm: 'Curium',
    Bk: 'Berkelium',
    Cf: 'Californium',
    Es: 'Einsteinium',
    Fm: 'Fermium',
    Md: 'Mendelevium',
    No: 'Nobelium',
    Lr: 'Lawrencium',
    Rf: 'Rutherfordium',
    Db: 'Dubnium',
    Sg: 'Seaborgium',
    Bh: 'Bohrium',
    Hs: 'Hassium',
    Mt: 'Meitnerium',
    Ds: 'Darmstadtium',
    Rg: 'Roentgenium',
    Cn: 'Copernicium',
    Nh: 'Nihonium',
    Fl: 'Flerovium',
    Mc: 'Moscovium',
    Lv: 'Livermorium',
    Ts: 'Tennessine',
    Og: 'Oganesson',
  },
});

/**
 * Grafias que a busca também aceita, fora a oficial.
 *
 * O nome em inglês segue a IUPAC — Aluminium, Caesium —, mas quem aprendeu
 * química nos Estados Unidos digita "aluminum" e "cesium". Sem isto, a busca
 * devolve a tabela vazia e a pessoa conclui que a ferramenta não tem o elemento.
 */
export const ELEMENT_SEARCH_ALIASES: Readonly<Record<string, readonly string[]>> = {
  Al: ['aluminum'],
  Cs: ['cesium'],
};

/** O nome do elemento no idioma de quem lê, ou o próprio símbolo se não houver. */
export function elementName(locale: Locale, symbol: string): string {
  const names = pick(elementNames, locale) as Readonly<Record<string, string | undefined>>;
  return names[symbol] ?? symbol;
}
